# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41151ba6bb570366e1ae7000ffeb717e0a872e846d953e21a25213fe30768a4790058827045ca52e0b732cd76e70b062dba47fcf868dddb6bd5f308a788a9bf8

test:
  secret_key_base: 311beb3e68d8e8e12e408fd250d9a5ace5f5433b4e33700c3295c5c9c824c3e85c4285183fca1e24fc4c8eb5b42c65a25ab3f3184644a8d7b625686ace8d7ca7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
